const IPC_CHANNELS = {
  tray: {
    setLanguage: 'tray:set-language',
    setLabels: 'tray:set-labels',
  },
  updater: {
    check: 'updater:check',
    openDownload: 'updater:open-download',
    getStatus: 'updater:get-status',
    status: 'updater:status',
  },
  app: {
    openExternal: 'app:open-external',
    openLocalConfig: 'app:open-local-config',
    openConfigDirectory: 'app:open-config-directory',
    exportOptionsConfig: 'app:export-options-config',
    importOptionsConfig: 'app:import-options-config',
    getInterfaceLayoutConfig: 'app:get-interface-layout-config',
    saveInterfaceLayoutConfig: 'app:save-interface-layout-config',
    getProviderConfigSnapshot: 'app:get-provider-config-snapshot',
    saveProviderConfigSnapshot: 'app:save-provider-config-snapshot',
    parseAttachment: 'app:parse-attachment',
    resetLocalData: 'app:reset-local-data',
    getLocalProxyBaseUrl: 'app:get-local-proxy-base-url',
    getLocalProxyConfig: 'app:get-local-proxy-config',
    syncLocalProxyConfig: 'app:sync-local-proxy-config',
    updateLocalProxyConfig: 'app:update-local-proxy-config',
    updateWindowBehavior: 'app:update-window-behavior',
    updateStartupAppearance: 'app:update-startup-appearance',
    getCliProviderStatus: 'app:get-cli-provider-status',
    syncCliProviderConfig: 'app:sync-cli-provider-config',
    runCliPrompt: 'app:run-cli-prompt',
    stopCliProvider: 'app:stop-cli-provider',
    cleanupCliSessions: 'app:cleanup-cli-sessions',
    appendRequestLog: 'app:append-request-log',
    queryRequestLogs: 'app:query-request-logs',
    clearRequestLogs: 'app:clear-request-logs',
  },
  storage: {
    readAppStorage: 'storage:read-app-storage',
    writeAppStorage: 'storage:write-app-storage',
    removeAppStorage: 'storage:remove-app-storage',
    getSessionSummaries: 'storage:get-session-summaries',
    getSession: 'storage:get-session',
    saveSession: 'storage:save-session',
    updateSessionTitle: 'storage:update-session-title',
    deleteSession: 'storage:delete-session',
    searchSessionSummaries: 'storage:search-session-summaries',
    getActiveSessionId: 'storage:get-active-session-id',
    setActiveSessionId: 'storage:set-active-session-id',
    clearActiveSessionId: 'storage:clear-active-session-id',
  },
  mcp: {
    getConfig: 'mcp:get-config',
    saveConfig: 'mcp:save-config',
    reload: 'mcp:reload',
    getServers: 'mcp:get-servers',
    listTools: 'mcp:list-tools',
    testConfig: 'mcp:test-config',
    callTool: 'mcp:call-tool',
    callSearch: 'mcp:call-search',
  },
  window: {
    minimize: 'window:minimize',
    toggleMaximize: 'window:toggle-maximize',
    close: 'window:close',
    rendererReady: 'window:renderer-ready',
    isMaximized: 'window:is-maximized',
    getAppVersion: 'window:get-app-version',
    getSystemLanguage: 'window:get-system-language',
    getSystemTheme: 'window:get-system-theme',
    maximize: 'window:maximize',
    unmaximize: 'window:unmaximize',
    systemThemeChanged: 'window:system-theme-changed',
    systemLanguageChanged: 'window:system-language-changed',
  },
};

const IPC_BOOTSTRAP_CHANNELS = {
  ipcChannels: 'app:bootstrap:ipc-channels',
  providerConfigSnapshot: 'app:bootstrap:provider-config-snapshot',
  interfaceLayoutConfigSnapshot: 'app:bootstrap:interface-layout-config-snapshot',
};

module.exports = {
  IPC_BOOTSTRAP_CHANNELS,
  IPC_CHANNELS,
};
