import type { RefObject } from 'react';
import type { ReasoningLevel } from '@/infrastructure/providers/types';
import type { ChatMessage, ChatPromptInput } from '@/shared/types/chat';
import type { SendShortcut } from '@/shared/utils/appOptions';
import type { Language } from '@/shared/utils/i18n';
import type { PetSettings } from '@client/features/pet/domain/petTypes';

export type ChatMainProps = {
  language: Language;
  sessionId: string;
  isSessionStateReady: boolean;
  messages: ChatMessage[];
  isStreaming: boolean;
  isLoading: boolean;
  messagesContentRef: RefObject<HTMLDivElement | null>;
  messagesContainerRef: RefObject<HTMLDivElement | null>;
  messagesEndRef: RefObject<HTMLDivElement | null>;
  showScrollToBottom: boolean;
  onJumpToBottom: () => void;
  onSendMessage: (input: ChatPromptInput) => void;
  onStopStreaming: () => void;
  reasoningEnabled: boolean;
  reasoningControlVisible: boolean;
  reasoningLevel: ReasoningLevel;
  reasoningLevelOptions: ReasoningLevel[];
  reasoningLevelSupported: boolean;
  reasoningToggleLocked: boolean;
  sendShortcut: SendShortcut;
  showMessageTimestamps: boolean;
  wrapCodeBlocks: boolean;
  petSettings: PetSettings;
  onReasoningLevelChange: (level: ReasoningLevel) => void;
  onToggleReasoning: () => void;
};
