export const BUILTIN_PROVIDER_IDS = [
  'openai',
  'openrouter',
  'poe',
  'google',
  'google-vertex',
  'groq',
  'together',
  'fireworks',
  'cerebras',
  'perplexity',
  'cohere',
  'sambanova',
  'mistral',
  'longcat',
  'anthropic',
  'vercel',
  'open-responses',
  'deepinfra',
  'huggingface',
  'alibaba',
  'amazon-bedrock',
  'azure-openai',
  'baseten',
  'nvidia-nim',
  'clarifai',
  'heroku',
  'lm-studio',
  'modelscope',
  'modal',
  'openadapter',
  'opencode',
  'openai-compatible',
  'xai',
  'deepseek',
  'glm',
  'minimax',
  'moonshot',
  'volcengine',
  'xiaomi-mimo',
  'stepfun',
  'mulerouter',
] as const;

export const PROVIDER_IDS = BUILTIN_PROVIDER_IDS;
