import type { ImageGenerationSettings } from '@/infrastructure/providers/imageGeneration/types';

export const DEFAULT_IMAGE_GENERATION_SETTINGS: ImageGenerationSettings = {
  count: 1,
  dimensionMode: 'size',
  size: '1024x1024',
  aspectRatio: '1:1',
  quality: 'auto',
  background: 'auto',
  outputFormat: 'png',
  outputCompression: 100,
  openAIStyle: 'none',
  openAIModeration: 'none',
  openAIUser: '',
  xaiResolution: '1k',
  googlePersonGeneration: 'allow_adult',
  togetherNegativePrompt: '',
  togetherDisableSafetyChecker: false,
  fireworksNegativePrompt: '',
  deepInfraNegativePrompt: '',
  falPromptOptimizer: false,
  falEnableSafetyChecker: true,
  falSyncMode: false,
  replicateNegativePrompt: '',
  replicateOutputFormat: 'png',
  blackForestLabsImagePrompt: '',
  blackForestLabsInputImages: '',
  blackForestLabsOutputFormat: 'png',
  blackForestLabsPromptUpsampling: false,
  blackForestLabsRaw: false,
  blackForestLabsWebhookUrl: '',
  blackForestLabsWebhookSecret: '',
  prodiaStylePreset: 'none',
  prodiaLoras: '',
  prodiaProgressive: false,
  lumaReferenceType: 'none',
  lumaReferenceImages: '',
  lumaReferenceId: '',
};

export const getDefaultImageGenerationSettings = (): ImageGenerationSettings => ({
  ...DEFAULT_IMAGE_GENERATION_SETTINGS,
});
